services:
  otterscan:
    image: otterscan/otterscan:latest
    container_name: otterscan
    environment:
      - ERIGON_URL=${PUBLIC_RPC_URL}
    ports:
      - '5100:80'
    restart: always
    networks:
      - pacmonnet
networks:
  pacmonnet:
    name: pacmonnet
    external: true
