services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - '5432:5432'
    restart: always
    networks:
      - pacmonnet
    volumes:
      - postgresdata:/var/lib/postgresql/data
  hardhat:
    build: hardhat
    ports:
      - '8545:8545'
    restart: always
    networks:
      - pacmonnet
    volumes:
      - postgresdata:/app/cache
networks:
  pacmonnet:
    name: pacmonnet
    external: true
volumes:
  postgresdata:
    driver: local
  hardhatdata:
    driver: local
