services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - '5432:5432'
    restart: always
    networks:
      - pacmonnet
    volumes:
      - postgresdata:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    restart: always
    networks:
      - pacmonnet
    volumes:
      - redisdata:/bitnami/redis/data

  erigon:
    # image: thorax/erigon:latest
    build:
      context: erigon
      dockerfile: erigon.Dockerfile
    ports:
      - '8551:8551'
    restart: unless-stopped
    command:
      - --datadir=dev
      - --chain=dev
      - --private.api.addr=0.0.0.0:9090
      - --mine
    networks:
      - pacmonnet
    volumes:
      - erigondata:/app/dev

  erigonrpc:
    # image: thorax/erigon:latest
    build:
      context: erigon
      dockerfile: rpcdaemon.Dockerfile
    ports:
      - '8545:8545'
    pid: service:erigon
    depends_on:
      - erigon
    restart: always
    command:
      - --datadir=dev
      - --http.addr=0.0.0.0
      - --private.api.addr=erigon:9090
      - --http.api=eth,erigon,ots,web3,net,debug,trace,txpool,parity
      - --http.trace
      - --http.vhosts=any
      - --http.corsdomain=*
      - --ws
    networks:
      - pacmonnet
    volumes:
      - erigondata:/app/dev

  otterscan:
    image: otterscan/otterscan:latest
    container_name: otterscan
    environment:
      - ERIGON_URL=${PUBLIC_RPC_URL}
    ports:
      - '5100:80'
    restart: always
    depends_on:
      - erigonrpc
    networks:
      - pacmonnet

  app:
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PW}@db:5432/${POSTGRES_DB}?schema=public
    environment:
      - APP_PORT=3000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PW=${POSTGRES_PW}
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PW}@db:5432/${POSTGRES_DB}?schema=public
      - PRIVATE_RPC_URL=http://erigonrpc:8545
      - PUBLIC_RPC_URL=${PUBLIC_RPC_URL}
      - REDIS_URL=redis://redis:6379
      - GITHUB_PLUGIN_OWNER=${GITHUB_PLUGIN_OWNER}
      - GITHUB_PLUGIN_REPO=${GITHUB_PLUGIN_REPO}
      - GITHUB_PLUGIN_PATH=${GITHUB_PLUGIN_PATH}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    ports:
      - '3033:3000'
    restart: always
    depends_on:
      - db
      - redis
      - erigonrpc
    networks:
      - pacmonnet
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  postgresdata:
    driver: local
  redisdata:
    driver: local
  erigondata:
    name: erigondata
    external: true
networks:
  pacmonnet:
    name: pacmonnet
    external: true
