openapi: 3.1.0
info:
  title: PACMON
  version: 0.0.1
servers:
  - url: http://localhost:3000
tags:
  - name: Template
    description: Solidity source code and configuration files for each step are provided to enable our automation engine to deploy them to the test node
paths:
  /projects:
    get:
      tags:
        - Project & Template
      summary: Get all projects
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProjectMinimal"
  /projects/{projectId}:
    get:
      tags:
        - Project & Template
      summary: Get project and all its templates
      parameters:
        - in: path
          name: projectId
          schema:
            type: integer
          required: true
          description: Numeric ID of the project
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
  /projects/create:
    post:
      tags:
        - Project & Template
      summary: Create project
      requestBody:
        description: Item to be created
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectCreateBody"
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
  /projects/update:
    post:
      tags:
        - Project & Template
      summary: Update project
      requestBody:
        description: Item to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectUpdateBody"
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
  /projects/delete:
    post:
      tags:
        - Project & Template
      summary: Delete project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: integer
                  format: int64
                  examples: [1, 2, 3, 4]
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    examples: [true]
  /projects/deploy:
    post:
      tags:
        - Project & Template
      summary: Deploy project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: integer
                  format: int64
                  examples: [1, 2, 3, 4]
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
  /node/info:
    get:
      tags:
        - Node
      summary: Get node info
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  rpc:
                    type: string
                    examples: ["http://localhost:8545"]
                  signers:
                    type: array
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                          examples: ["0x1234567890"]
                        privateKey:
                          type: string
                          examples:
                            [
                              "0x1234567890123456789012345678901234567890123456789012345678901234567890",
                            ]
  /node/reset:
    post:
      tags:
        - Node
      summary: Reset node to initial state
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    examples: [true]

components:
  schemas:
    ProjectCreateBody:
      type: object
      properties:
        name:
          type: string
          examples: [Pacmon, Pragma, Papaya]
        templates:
          type: array
          items:
            $ref: "#/components/schemas/TemplateBody"
      required:
        - name
        - templates
    ProjectUpdateBody:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [1, 2, 3, 4]
        name:
          type: string
          examples: [Pacmon, Pragma, Papaya]
        templates:
          type: array
          items:
            $ref: "#/components/schemas/TemplateBody"
      required:
        - id
        - name
        - templates
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [1, 2, 3, 4]
        name:
          type: string
          examples: [Pacmon, Pragma, Papaya]
        templates:
          type: array
          items:
            $ref: "#/components/schemas/Template"
    ProjectMinimal:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [1, 2, 3, 4]
        name:
          type: string
          examples: [Pacmon, Pragma, Papaya]
        templates:
          type: array
          items:
            $ref: "#/components/schemas/TemplateMinimal"
    Template:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [1, 2, 3, 4]
        script:
          type: string
          examples: ["// SOLIDITY CODE"]
        configuration:
          type: string
          examples: ["// YAML CONFIG"]
        sequence:
          type: integer
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
          default: ACTIVE
        address:
          type: string
          nullable: true
          examples: ["0x1234567890"]
        projectId:
          type: integer
          format: int64
          examples: [1, 2, 3, 4]
    TemplateBody:
      type: object
      properties:
        script:
          type: string
          examples: ["// SOLIDITY CODE"]
        configuration:
          type: string
          examples: ["// YAML CONFIG"]
        sequence:
          type: integer
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
      required:
        - script
        - configuration
        - sequence
    TemplateMinimal:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [1, 2, 3, 4]
        sequence:
          type: integer
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
          default: ACTIVE
        address:
          type: string
          nullable: true
          examples: ["0x1234567890"]
        projectId:
          type: integer
          format: int64
          examples: [1, 2, 3, 4]
