openapi: 3.1.0
info:
  title: PACMON
  version: 0.0.1
servers:
  - url: https://localhost:3000
tags:
  - name: Template
    description: Solidity source code and configuration files for each step are provided to enable our automation engine to deploy them to the test node
paths:
  /templates/list:
    get:
      tags:
        - Template
      summary: Get all existing template
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Template"
  /templates/create:
    post:
      tags:
        - Template
      summary: Create template
      requestBody:
        description: Item to be created
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemplateBody"
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
  /templates/deploy:
    post:
      tags:
        - Template
      summary: Deploy template
      requestBody:
        description: Provide ID of Template & Node to be deployed
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                templateId:
                  type: string
                  required: true
                nodeId:
                  type: string
                  required: true
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
components:
  schemas:
    Template:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [1, 2, 3, 4]
        script:
          type: string
        configuration:
          type: string
        sequence:
          type: integer
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
          default: ACTIVE
    TemplateBody:
      type: object
      properties:
        script:
          type: string
        configuration:
          type: string
        sequence:
          type: integer
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
      required:
        - script
        - configuration
        - sequence
